bearmq:
  username: ejjovbanrshkwzfvkiiixtfjrrott
  password: jpFmIejRinsVlHbfnySWQTcnVIiFj
  host: localhost
  port: 6667
  virtual-host: admin-tocrvrtxbbtpzvenyhehdkifuisoc
  api-key: bearmqt-mdOyXnaNaPJXrmbRTmDrHlPoMLGffUEIYHRVHfuUMxEE
logging:
  level:
    root: warn