bearmq:
  username: rxucpxtkyazeqhwuhnylp
  password: EZnqbfMEBRmtiVRKRqXJg
  host: localhost
  port: 6667
  virtual-host: admin-rtxbionamwsxaftecspgo
  api-key: bearmqt-bootstrap-change-me
logging:
  level:
    root: warn