bearmq:
  username: mnckbihpvuymdmpwvzsgohwedtg
  password: DudFrjmbTHAreLiDKlHZcFsrOUZ
  host: bearmq.nuricanozturk.com
  port: 6667
  virtual-host: admin-xdnmntyywmskyrzumlmhziscrdx
  api-key: bearmqt-LqKOVVGrwwEZgbIBCbJSfIZAZSDndgssJbeJYwUxXENV
  rest-port: 443
logging:
  level:
    root: warn