server:
  port: 2222
app:
  exchange: exchangeA
  queue: queueZ
  queuet: queueT

bearmq:
  username: enhlgcdcflttdkizu
  password: gwzRYzGQqrgGDTUrF
  host: localhost
  port: 6667
  virtual-host: OZTURK-vjykrtzpzsfawlwbs
  api-key: bearmqt-BAoCQtQKeDpbfaVVmphyFQfWyqbGwAwAJNoVaUfQlvZi

