server:
  port: 2222
app:
  exchange: exchangeA
  queue: queueZ
  queuet: queueT

bearmq:
  username: mnckbihpvuymdmpwvzsgohwedtg
  password: DudFrjmbTHAreLiDKlHZcFsrOUZ
  host: bearmq.nuricanozturk.com
  port: 6667
  virtual-host: admin-xdnmntyywmskyrzumlmhziscrdx
  api-key: bearmqt-LqKOVVGrwwEZgbIBCbJSfIZAZSDndgssJbeJYwUxXENV
  rest-port: 443

