server:
  port: 2222
app:
  exchange: exchangeA
  queue: queueZ
  queuet: queueT

bearmq:
  username: ejjovbanrshkwzfvkiiixtfjrrott
  password: jpFmIejRinsVlHbfnySWQTcnVIiFj
  host: localhost
  port: 6667
  virtual-host: admin-tocrvrtxbbtpzvenyhehdkifuisoc
  api-key: bearmqt-mdOyXnaNaPJXrmbRTmDrHlPoMLGffUEIYHRVHfuUMxEE

